name: CI deploy

on:
  push:
    branches:
      - main
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: Install and Build
        run: |
          pnpm install --ignore-scripts --fix-lockfile
          pnpm run build

      - name: Fix 404 on GitHub Pages
        run: |
          sed -i "s/.\/assets/\/assets/" dist/index.html
          cp dist/index.html dist/404.html

          cat <<EOF > script.js
              <script type="text/javascript">
                  (function(l) {
                      const matchPreviewDeployment = l.pathname.match(/preview\/pr-\d+/);
                      if (matchPreviewDeployment) l.replace(l.origin + "/" +matchPreviewDeployment[0]);
                  }(window.location))
              </script>
            </head>
          EOF
          
          sed -i '/<\/head>/ {
              r script.js
              d
          }' dist/404.html
          
          rm script.js

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist/
          branch: gh-pages
          clean-exclude: preview
